### ISSUE TITLE
 jrottenberg/ffmpeg:4.0-alpine does not output to stdout

### ISSUE THREAD

**Issue by marcuslindblom** [jrottenberg/ffmpeg#104]
I use this command with `jrottenberg/ffmpeg:3.3-alpine` which works fine but using the `4.0` release does not produce any output?

`docker run jrottenberg/ffmpeg:4.0-alpine -stats -i http://techslides.com/demos/sample-videos/small.mp4 -f mjpeg -vf select='not(mod(n\,3))',yadif,scale=480:-1,crop=iw:270,tile=1x50 -q:v 5 -vframes 1 - > scrub.jpg`

**Comment by GnaphronG** [comment]
The q:v parameter is the problem with the alpine version of the container. This use the musl libc instead of the gnu-libc in order to be smaller. 
I don't have a proper solution that might require some changes at the ffmpeg level.

As a workaround you can replace `-q:5` by `-qmin 5 -qmax 5` it will produce the same output quality.

**Comment by marcuslindblom** [comment]
Sweet, this worked like a charm!

@jrottenberg I can see that the alpine 4.0 hasn't been updated in a while on Dockerhub, do you still maintain this image?

**Comment by jrottenberg** [comment]
I do maintain it but the free plan for dockerhub is failing compilation from time to time... With that number of variants, it's tedious to verify all of them built properly
