### ISSUE TITLE
CentOS base has outdated CMAKE

### ISSUE THREAD

**Issue by ILOVEPIE** [jrottenberg/ffmpeg#157]
May need to update the CentOS base's version, currently this is blocking #155 and preventing a pass on the checks.

**Comment by jrottenberg** [comment]
I see : 
```
  CMake 3.5 or higher is required.  You are running version 2.8.12.2
```

The centos variant from is `7` so not much we can do there at the from level, maybe : 

```
yum -y install epel-release
yum install cmake3
```

**Comment by hvindin** [comment]
I've just opened 2 PR's which should both fix the version of cmake required to build x265.

Using a centos:8 base container feels like an ok thing to do given that it's just the latest release of centos, but may cause issues for anyone who has forked off and gone and done their own thing assuming centos:7

Just using cmake3 rather than cmake _seems_ to work, but I'm not sure if it might cause some weird error in the built files because a lib detected centos v7 and configured itself assuming cmake v2 (I've seen it happen, and it's a terrible thing to put in your build scripts, but I guess if it works...)

They should both technically fix the cmake issue...

The other alternative would be to make `cmake` (as in the command) a variable, then for all of the other templates set it to `cmake` and for the centos container set it to `cmake3`, or possibly at an even more specific level for this issue set it to `cmake` for all of the builds _except_ the ones which need `cmake3` and just have two `cmake` variables, both set to `cmake` for every other distro, but set differently in centos. Feels like it would get very complicated very fast though...
