### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by dprestegard** [jrottenberg/ffmpeg#217]
Hello!

Seems the CentOS variant of this wonderful image recently jumped up to CentOS 8. This has broken some stuff for me. Can we get a version pinned to CentOS 7?

**Comment by jrottenberg** [comment]
oh !

That's a good point we should build the full semver version, and tag it with Major and Major + Minor as well.

What issue do you have withe the build on centos8 ? 

But yeah, jrottenberg/ffmpeg:3.1-centos is centos7

**Comment by dprestegard** [comment]
My app takes your image and layers in some binaries that are officially only supported on centos 7, unfortunately

**Comment by hvindin** [comment]
Pinned major versions would make sense for centos-7/centos-8

Although to make builds happy on centos-7 is a bit more complicated that centos-8 due to centos-7 having a particularly ancient cmake version installed and cmake 3.x is literally installed as cmake3... but I can't imagine that throwing in an alternatives --install would break any of the subsequent build steps...

**Comment by hvindin** [comment]
@dprestegard if you explicitly specify centos7 in the container tag is your problem now resolved?

**Comment by dprestegard** [comment]
Looks good. It turns out my app actually _does_ work fine in centos 8, despite what the vendor says. Go figure

**Comment by hvindin** [comment]
I have found that to be the case between EL versions a few times... although EL8 is a pretty huge shift from EL7...
